#! /bin/bash

actions="firefox
st
chromium-browser
thunar
subl
gimp
pavucontrol"
result=$(echo "$actions" | dmenu -h 35 -l 10 -w 500 -x 418 )
cmd=$(echo "$result")
[ -n "$cmd" ] && eval setsid setsid "$cmd"
