#! /bin/bash

#
# 		usage :
#		dmenu_startmenu $font $nbg $nfg $selbg $selfg
#

actions="firefox
st
chromium-browser
thunar
subl
gimp"
result=$(echo "$actions" | dmenu -h 30 -i -b )
cmd=$(echo "$result")
[ -n "$cmd" ] && eval setsid setsid "$cmd"
