#!/bin/sh

# basic session settings
xrdb ~/.Xresources &
compton &
#xrandr --output DP1 --rotate left --left-of HDMI3 &
#xset b off &
#pulseaudio -D &

# wallpaper
# hsetroot -solid "#000000" &		 	
feh --bg-fill $HOME/Pictures/wallpaper.jpg &

# window manager
dwmstatus &
exec dwm
